/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Source file was org.deepin.ai.daemon.VectorIndex.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "vectorindex.h"

/*
 * Implementation of interface class OrgDeepinAiDaemonVectorIndexInterface
 */

OrgDeepinAiDaemonVectorIndexInterface::OrgDeepinAiDaemonVectorIndexInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgDeepinAiDaemonVectorIndexInterface::~OrgDeepinAiDaemonVectorIndexInterface()
{
}


#include "moc_vectorindex.cpp"
